name: Cabal Tests

on:
  push:
  pull_request:

jobs:
  cabal-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Haskell with Cabal
        uses: haskell/setup@v2
        with:
          ghc-version: '9.6.5'
          cabal-version: '3.10.2.0'

      - name: Cache Cabal artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal
            dist-newstyle
          key: ${{ runner.os }}-cabal-${{ hashFiles('cabal.project', 'typus.cabal') }}
          restore-keys: |
            ${{ runner.os }}-cabal-

      - name: Update Cabal package list
        run: cabal update

      - name: Run Cabal tests
        run: cabal test --test-show-details=direct

  cabal-test-production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Haskell with Cabal
        uses: haskell/setup@v2
        with:
          ghc-version: '9.6.5'
          cabal-version: '3.10.2.0'

      - name: Cache Cabal artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal
            dist-newstyle
          key: ${{ runner.os }}-cabal-${{ hashFiles('cabal.project', 'typus.cabal') }}
          restore-keys: |
            ${{ runner.os }}-cabal-

      - name: Update Cabal package list
        run: cabal update

      - name: Run Cabal tests with production flags
        run: cabal test --flags="-fast production" --test-show-details=direct
